### PR TITLE
Move main code of sc-builder to separate sc-builder-lib

### PR DESCRIPTION
**Pull request by KovalM**
* [ ] Read PR [documentation](http://ostis-dev.github.io/sc-machine/dev/pr/)
* [ ] Update changelog
* [ ] Update documentation

This update needed for using for use scs loader outside builder. We use scs loader for write tests for agents

Merge after #323

### CODE REVIEW

**Comment by deniskoronchik** [comment]
I have no idea, why we need to split builder code to library and executable

**Comment by KovalM** [comment]
> I have no idea, why we need to split builder code to library and executable

As I wrote in pull request description, we need to use scs loader for write tests of agents. In this tests we load test sc-constructions from scs-files. 

I don't found way to include executable in app library outside sc-machine. That's why I decided to split builder code to library and executable.

**Comment by deniskoronchik** [comment]
Test should not depend on builder tool code.  Use SCsHelper instead

**Comment by KovalM** [comment]
> Test should not depend on builder tool code. Use SCsHelper instead

SCsHelper doesn't support load from scs-file, only from scs text . Do you propose move this logic to SCsHelper or duplicate code for loading scs from file in our tests?

**Comment by deniskoronchik** [comment]
> > Test should not depend on builder tool code. Use SCsHelper instead
> 
> SCsHelper doesn't support load from scs-file, only from scs text . Do you propose move this logic to SCsHelper or duplicate code for loading scs from file in our tests?

Loading of file is 3 lines of code: 
```cpp
std::ifstream ifs("myfile.txt");
std::string content(std::istreambuf_iterator<char>(ifs), std::istreambuf_iterator<char>());
```

**Comment by KovalM** [comment]
> > > Test should not depend on builder tool code. Use SCsHelper instead
> > 
> > 
> > SCsHelper doesn't support load from scs-file, only from scs text . Do you propose move this logic to SCsHelper or duplicate code for loading scs from file in our tests?
> 
> Loading of file is 2 lines of code:
> 
> ```c++
> std::ifstream ifs("myfile.txt");
> std::string content(std::istreambuf_iterator<char>(ifs), std::istreambuf_iterator<char>());
> ```
> 
> My proposal to do not add this function into SCsHelper and read file content in a test framework.

Your code returns empty string in case when file is not exist. The same behavior for empty file and no file can lead to issues. 
Also, this code need for check on throwing I/O exceptions. I think code from Translator::GetFileContent is more safely for use.

About using ScsHelper. For initialize it we need to provide some SCsFileInterface entity. sc-builder use FileProvider, it is too much code for duplicate it in our test framework. 

I propose to think about sharing part of sc-builder code.

**Comment by KovalM** [comment]
Closed after discussion on the call

**Pull request closed without merging**
