### PR TITLE
CMake improvements

### PR DESCRIPTION
**Pull request by fintarin**
* [x] Read PR [documentation](http://ostis-dev.github.io/sc-machine/dev/pr/)
* [ ] Update changelog
* [ ] Update documentation

### CODE REVIEW

**Comment by deniskoronchik** [comment]
Please rebase onto master without commits from other PR's

**Comment by fintarin** [comment]
It's pretty hard to rebase this commit without #405

**Comment by deniskoronchik** [comment]
We wouldn't merge #405 in short period. We need to discuss our goals with CMake formatting and determine suitable config. That will take time.

**Comment by fintarin** [comment]
This commit is a logical continuation of #405, so I guess it can wait.

**Pull request closed without merging**
