### PR TITLE
Add ability include directory SC_KPM_SCR outside for use code from this dir

### PR DESCRIPTION
**Pull request by KovalM**
* [ ] Read PR [documentation](http://ostis-dev.github.io/sc-machine/dev/pr/)
* [ ] Update changelog
* [ ] Update documentation

### CODE REVIEW

**Comment by deniskoronchik** [comment]
Why we need that?

**Comment by KovalM** [comment]
> Why we need that?

We need to use code from sc-kpm dir outside. We need to use this dir in include_directories() as we do it for sc-memory including

**Comment by deniskoronchik** [comment]
What use sc-kpm outside this directory?

**Comment by KovalM** [comment]
> What use sc-kpm outside this directory?

Our apps that use code from sc-kpm. We place sc-agents-common lib in sc-kpm.

**Comment by KovalM** [comment]
Closed after discussion on the call

**Pull request closed without merging**
