### PR TITLE
Allow build from file with source folders list

### PR DESCRIPTION
**Pull request by MikhailSadovsky**
* [ ] Read PR [documentation](http://ostis-dev.github.io/sc-machine/dev/pr/)
* [ ] Update changelog
* [ ] Update documentation

### CODE REVIEW

**Review by KovalM — APPROVED** [review]

**Comment by deniskoronchik** [comment]
What does this fix do?

**Review by deniskoronchik — CHANGES_REQUESTED** [review]
Need to figure out a goal of this fix

**Comment by MikhailSadovsky** [comment]
> What does this fix do?

The fix allows build from regular file with multiple source folders specified. [`CollectFiles()`](https://github.com/ostis-dev/sc-machine/blob/master/tools/builder/src/builder.cpp#L240) method was called after removed code:

```
bool Builder::Run(BuilderParams const & params)
{
  m_params = params;

  // check
  if (!boost::filesystem::is_directory(m_params.m_inputPath))
  {
    ScConsole::PrintLine() << ScConsole::Color::White
      << "Directory " << ScConsole::Color::Red 
      << m_params.m_inputPath << ScConsole::Color::White 
      << " doesn't exist";

    return false;
  }

  CollectFiles();
```
It supports both directory & regular file as an input:
```
void Builder::CollectFiles()
{
  m_files.clear();
  if (boost::filesystem::is_directory(m_params.m_inputPath))
  {
    CollectFiles(m_params.m_inputPath);
  }
  else if (boost::filesystem::is_regular_file(m_params.m_inputPath))
  {
         .....
        // process every specified directory in file
  }
}
```
So the removed peace of code just enables file option again as it was supported

**Comment by deniskoronchik** [comment]
In that case it is better to improve check and error message than just remove it.

**Comment by MikhailSadovsky** [comment]
> In that case it is better to improve check and error message than just remove it.

Updated with `exists` method usage & new message

**Review by deniskoronchik — APPROVED** [review]

**Pull request merged**
